name: 'MAUIAppVersion'
description: 'Bump ApplicationVersion and ApplicationDisplayVersion'
inputs:
  csproj:
    description: 'Path to csproj file'
    required: true
    default: '1'
  version:
    description: 'Value for ApplicationVersion property'
    required: false
    default: '1'
  displayVersion:
    description: 'Value for ApplicationVersion property'
    required: false
    default: '1.0'
  printFile:
    description: 'Print file content'
    required: false
    default: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'