name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  
  action-test:
    runs-on: macos-latest
    
    steps:

      - uses: actions/checkout@v3

      - id: foo
        uses: actions/managedcode/BumpMAUIAppVersion@v1
        with:
          csproj: tests/MauiApp.csproj
          version: ${{ github.run_number }}
          displayVersion: '100.500'