name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  
  action-test:
    runs-on: macos-latest
    
    steps:

      - uses: actions/mauiappversion@v3

      - name: MAUIAppVersion
        uses: managedcode/MAUIAppVersion@v0.0.2-alpha
        with:
          csproj: tests/MauiApp.csproj
          version: ${{ github.run_number }}
          displayVersion: '100.500'